import logo01 from "/images/Companys/Companys-name/01.svg";
import logo02 from "/images/Companys/Companys-name/02.svg";
import logo03 from "/images/Companys/Companys-name/03.svg";
import logo04 from "/images/Companys/Companys-name/04.svg";
import logo05 from "/images/Companys/Companys-name/05.svg";
import logo06 from "/images/Companys/Companys-name/06.svg";
import logo07 from "/images/Companys/Companys-name/07.svg";
import logo08 from "/images/Companys/Companys-name/08.svg";
import logo09 from "/images/Companys/Companys-name/09.svg";
import prof01 from "/images/Companys/user-profile/01.webp";
import prof02 from "/images/Companys/user-profile/02.webp";
import prof03 from "/images/Companys/user-profile/03.webp";
import prof04 from "/images/Companys/user-profile/04.webp";
import prof05 from "/images/Companys/user-profile/05.webp";
import prof06 from "/images/Companys/user-profile/06.webp";
import prof07 from "/images/Companys/user-profile/07.webp";
import prof08 from "/images/Companys/user-profile/08.webp";
import prof09 from "/images/Companys/user-profile/09.webp";

const filterBox = [
  {
    id: 1,
    logo: logo01,
    desc: "As a content creator, I was always on the lookout for a tool that could help me keep up with the demand. The AI-driven content tool has been a game-changer. It generates high-quality content in a fraction of the time it used to take me.",
    createBy: "MaKayla P.",
    profile: prof01,
    sons: "Disney",
    status: "ecommerce",
  },
  {
    id: 2,
    logo: logo02,
    desc: "I've tried several content generation tools, but this AI-driven tool is by far the best. It understands my brand's voice and consistently produces content that resonates with my audience!",
    createBy: "Andrew K.",
    profile: prof02,
    sons: "Samsung",
    status: "web apps",
  },
  {
    id: 3,
    logo: logo03,
    desc: "Content creation used to be a bottleneck in our workflow, but not anymore. This AI tool is intuitive and produces top-notch content every time. It's like having an extra team member who never sleeps! Definitely recommend.",
    createBy: "Lucy D. ",
    profile: prof02,
    sons: "Rio",
    status: "web apps",
  },
  {
    id: 4,
    logo: logo04,
    desc: "The quality of the content generated by this AI tool is outstanding. It has taken our content marketing to new heights, allowing us to publish more frequently without compromising on quality. Highly recommended for anyone.",
    createBy: "Pavel M.",
    profile: prof04,
    sons: "Canon",
    status: "enteprise",
  },
  {
    id: 5,
    logo: logo05,
    desc: "The AI-driven content tool has been a lifesaver for my marketing agency. We can now produce high-quality content for multiple clients quickly and efficiently. It's an invaluable asset to our team.",
    createBy: "Miriam E.",
    profile: prof05,
    sons: "Cadbury",
    status: "ecommerce",
  },
  {
    id: 6,
    logo: logo06,
    desc: "I'm amazed at how well this AI-driven content tool performs. It's incredibly versatile and can generate content for blogs, social media, and even product descriptions effortlessly. It's fantastic!",
    createBy: "Eloise V.",
    profile: prof06,
    sons: "Maffell",
    status: "ecommerce",
  },
  {
    id: 7,
    logo: logo07,
    desc: "I was blown away by how easy it was to create my content using this tool! Within a few hours, I had a professional-looking platform up and running, and my client could not believe it.",
    createBy: "Pierre-Gilles L.",
    profile: prof07,
    sons: "Binance",
    status: "web apps",
  },
  {
    id: 8,
    logo: logo08,
    desc: "I've never been a fan of complicated website AI tools, which is why Open PRO is perfect for me. Its minimalist design and simple functionality make staying organized feel like second nature..",
    createBy: "Danielle K.",
    profile: prof08,
    sons: " Forbes Inc.",
    status: "web apps",
  },
  {
    id: 9,
    logo: logo09,
    desc: "I've never been one for coding, so finding an AI tool that doesn't require any technical skills was a dream come true. This tool exceeded my expectations, and I'm proud to show off my new stuff to friends.",
    createBy: "Mary P.",
    profile: prof09,
    sons: "Ray Ban",
    status: "web apps",
  },
];

export default filterBox;
